### ISSUE TITLE
<img> attributes missing in <svg>

### ISSUE THREAD

**Issue by mauriciabad** [theGC/html-webpack-inline-svg-plugin#26] opened 2020-05-05 19:18 UTC
Hi I found this bug and a workaround.

### Not working example
Missing class attribute:
```html
<!-- input -->
<img inline class="small" src="example.svg" alt="">

<!-- output -->
<svg alt="">...</svg>
```

### Working example
Class attribute ok:
```html
<!-- input -->
<img inline src="example.svg" alt="" class="small">

<!-- output -->
<svg alt="" class="small">...</svg>
```

Notice that the position of `class="small"` affects the result.

**Comment by AntonioRedondo** [comment] 2020-05-21 13:46
Hi @mauriciabad, you are missing the symbol `=` on `src"example.svg"`. Could this be the cause for the bug?

**Comment by mauriciabad** [comment] 2020-05-21 14:23
Good eye, but no. 😢 It's a mistake I did while writing the example. I tested it with the `=` and it's still not working.

I'll edit the issue to avoid confusion.

**Comment by AntonioRedondo** [comment] 2021-08-01 23:16
I've tried to replicate the reported behaviour on the project tests. But no matter the order of attributes they're always properly mapped correctly to the inlined SVG.

I'm closing this issue. It's however still accessible to anyone who may experience this behaviour.

**Closed by AntonioRedondo** 2021-08-01 23:16 UTC
